### ISSUE TITLE
Discrete parameters optimization

### ISSUE THREAD

**Issue by YamLyubov** [aimclub/iOpt#101]
While working on #89 I ran into a problem with optimizing categorical and discrete parameters (e.g.  RandomForest has param ```criterion``` with options '```["gini", "entropy"]``` and param  ```min_samples_split``` that can be an int from 2 to inf).

Now class ```Problem``` contains such attributes as ```discreteVariableValues``` and ```discreteVariableNames``` but ```Solver``` doesn't seem to optimize them. 
- Can such parameters be optimized now?
- How can I correctly specify possible values for discrete variables (```Problem.discreteVariablesValues```)?

**Comment by alvls** [comment]
В настоящий момент работа с дискретными параметрами в фреймворке не реализована. Метод, способный решать задачи оптимизации с дискретными параметрами, по текущему плану развития фреймворка будет реализован в течение 2023 года.

**Comment by alvls** [comment]
Реализовано.
