### ISSUE TITLE
Add timeout

### ISSUE THREAD

**Issue by YamLyubov** [aimclub/iOpt#104]
Было бы полезно для практического применения иметь возможность задавать ограничение на время поиска параметров.
Например, чтобы была возможность передавать timeout через ```SolverParameters```, как максимальное количество времени в минутах (пример для 5 минут). 
```
solver_parameters = SolverParameters(timeout=5)
```
Так чтобы, не смотря на то, что не все заданные итерации были пройдены, алгоритм принудительно завершается по истечение заданного времени.

**Comment by nicl-nno** [comment]
Это так, но когда мы применяем iOpt в рамках постановки AutoML - то нам более естественно ограничивать именно время. Потому что в итерациях оценить время работы AutoML довольно затруднительно (особенно если он интегрирует несколько алгоритмов)

Поэтому было бы очень полезно иметь такую опцию (не исключая при этом и альтернативного варианта с итерациями)

**Comment by alvls** [comment]
Хорошо. Попробуем добавить такую возможность.

**Comment by kozinove** [comment]
Добавлен прототип timeout 
Пример использлвания
https://github.com/aimclub/iOpt/blob/main/examples/GKLS_timeout_example.py

**Comment by alvls** [comment]
Реализовано.
