### ISSUE TITLE
Rename methods and variables PEP8

### ISSUE THREAD

**Issue by YamLyubov** [aimclub/iOpt#117]
Сейчас в проекте названия методов пишутся с помощью `CapWords`, атрибуты классов и аргументы функций c помощью `mixedCase`. [PEP8 рекомендует](https://peps.python.org/pep-0008/#naming-conventions) использовать во всех этих случаях `camel_case`, но допускает использование использование mixedCase, в следующем случае:
> mixedCase is allowed only in contexts where that’s already the prevailing style (e.g. threading.py), to retain backwards compatibility.

Однако, такое именование приводит к тому, что при использовании  IOpt в других проектах, которые в основном следуют pep8, нарушается консистентность нейминга. [Например в GOLEM.](https://github.com/aimclub/GOLEM/blob/iopt-tuner/golem/core/tuning/iopt_tuner.py#L73-L79)

Хотела бы предложить:

- привести именования в соответствие PEP8 к `snake_case`

Заодно

- почистить проект от закоментированого кода ([пример](https://github.com/aimclub/iOpt/blob/main/iOpt/method/process.py#L150-L157)) и неинформативных комментариев ([пример](https://github.com/aimclub/iOpt/blob/main/iOpt/method/method.py#L141))
- некоторые коментарии заменить на TODO ([пример](https://github.com/aimclub/iOpt/blob/main/iOpt/method/process.py#L146))
- поправить типизацию и значение по умолчанию в некогорых методах (иногда в качестве значений по умолчанию используются изменяемые типы, что [может вести к ошибкам](https://florimond.dev/en/posts/2018/08/python-mutable-defaults-are-the-source-of-all-evil/))

Возможно стоит подключить[ pep8speaks](https://pep8speaks.org/), чтобы было проще следить за code style

**Comment by YamLyubov** [comment]
Я готова заняться всем перечисленным (или какой-то частью). Хотела бы узнать, что думаете об этом)

**Comment by alvls** [comment]
Любовь, спасибо за комментарии! Давайте для начала мы попробуем сами их отработать. Если понадобится помощь, обратимся.

**Comment by alvls** [comment]
> Любовь, спасибо за комментарии! Давайте для начала мы попробуем сами их отработать. Если понадобится помощь, обратимся.

В продолжение. У нас сейчас активная фаза разработки новых методов. Как она закончится (ориентировочно в течение месяца или полутора), займемся приведение стиля кода по всему проекту. А пока будем локально править.

**Comment by alvls** [comment]
Выпущен новый релиз. В том числе внесены исправления по стилю кодирования.
