### ISSUE TITLE
Не работает таймаут

### ISSUE THREAD

**Issue by YamLyubov** [aimclub/iOpt#153]
При использовании параметра timeout `solver.Solve()` возвращает None. Кажется, [эту строчку](https://github.com/aimclub/iOpt/blob/main/iOpt/solver.py#L62) нужно исправить на `sol = solv_with_timeout()`. После исправления все заработало.

**Comment by YamLyubov** [comment]
Еще было бы удобно задавать таймаут через float (например 0.2 минуты). Попробовала позадавать нецелые таймауты - вроде работает, просто ругается на неправильный тип.

**Comment by YamLyubov** [comment]
Обнаружила еще следующие особенности:
- ставлю ограничение 20 итераций -> получаю 45 итераций (как я поняла они возникают на этапе `FirstIteration` в этой строчке https://github.com/aimclub/iOpt/blob/main/iOpt/method/method.py#L175C3-L175C3)
- ставлю ограничение в одну минуту -> получаю следующую ошибку (видимо первая итерация не успевает закончиться). Если `ConsoleOutputListener` убрать, то все-равно `solution.bestTrials[0].point` это пустой список
![image](https://github.com/aimclub/iOpt/assets/43475193/384ec2c5-0109-420e-83ec-45faca757628)

**Comment by alvls** [comment]
В релиз 0.2.2 внесены правки в работу с timeout.

**Comment by nicl-nno** [comment]
@YamLyubov можно закрывать, правки помогли?

**Comment by YamLyubov** [comment]
Ошибка теперь не падает, но все же колличество итераций и заданное время может быть превышено. Я так поняла, что это связано с тем, что на первой итерации перебираются все возможные комбинации дискретных параметров, при этом максимальное количество итераций и таймаут как бы игнорируются.
