### ISSUE TITLE
Папка  iOpt/examples устанавливается как отдельная библиотека.

### ISSUE THREAD

**Issue by SoloWayG** [aimclub/iOpt#188]
Доброго дня, устанавливал зависимости для GOLEM и установил IOpt через pip. После чего, при попытке импортировать модули из папки GOLEM/examples... (из папки моего рабочего проекта) словил ошибку "module not found". Происходит это по той причине, что в PATH python путь до venv/Lib/Site-packeges стоит одним из первых, из-за чего python находит модуль examples в Site-packeges первым. И если добавлять путь до рабочей директории проекта через sys.path.append(), то это не помогает, так как уже найдет модуль examples. Если первым будет путь до рабочего проекта, то из examples от iOpt будет невозможно импортировать что-то.
Собственно вопрос/предложение в следующем: Нужно ли устанавливать папку iOpt/examples как отдельную библиотеку? Если нет необходимости, то может добавить в исключение эту папку? Если все же она как-то нужна, то может переименовать ее, чтобы не возникало конфликтов?
![image](https://github.com/aimclub/iOpt/assets/113540469/a9b01332-2cf7-4d57-90b0-baea371d38a8)
![image](https://github.com/aimclub/iOpt/assets/113540469/35b39014-6a51-471a-ac57-5b64c1787983)

**Comment by kozinove** [comment]
Выложен новый релиз https://pypi.org/project/iOpt/
В релизе убрали папки из сборки

**Comment by SoloWayG** [comment]
Проверил на Python 3.8 - пишет что iOpt==0.4.0 нельзя поставить на python 3.8 и устанавливает iOpt==0.3.0 через ```pip install iOpt```, где описанная проблема сохраняется.
![image](https://github.com/aimclub/iOpt/assets/113540469/2f3e47c0-6750-45a0-93da-fd5afe8faffe).
Однако, на python 3.9 теперь все работает.

**Comment by kozinove** [comment]
3.8 сейчас использовать нельзя в связи с переходом к новой версии процессов в параллельном исполнении

**Comment by SoloWayG** [comment]
Хорошо.
