### ISSUE TITLE
Тесты - навести порядок в структуре.

### ISSUE THREAD

**Issue by LebedevIlyaG** [aimclub/iOpt#87]
Cтруктура папок и расположение самих тестов должно соответствовать пакету iOpt.

Переименовать "test/problem" в "test/problems" (Козинов, Лебедев)

Переместить "test/test_evolvent.py" и тестовые данные "test/evolventTestData" в "test/iOpt/evolvent/" (Штанюк)
Переместить  "test/test_optim_task.py" в "test/iOpt/method/test_optim_task.py" (Силенко)

Также нужно дописать тесты на классы:
1. Solver - проверка получения результата, проверка одной итерации и т.д. (Кудрявцев)
2. Process - на все методы, сейчас этот класс не протестирован.  (Черных?)
3. OptimizationTask - проверить вычисление задачи с ограничениями. (Силенко)

**Comment by alvls** [comment]
Реализовано.
